package modelos;

public enum Evento {
    MOSTRAR_MENU,
    JUGAR_CARTA,
    IRSE_AL_MAZO,
    RESPONDER_APUESTA,
    DIJO_QUIERO,
    DIJO_NO_QUIERO,
    FIN_RONDA,
    FIN_MANO,
    CAMBIO_TURNO,
    RESULTADO_ENVIDO,
    FIN_PARTIDA,
}
